<a href="https://colab.research.google.com/github/rmertoztop/project_4/blob/Jacob/Edited_ML_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup Tools and Environment

In [1]:
import os
# Find the latest version of spark 3.x  from http://www.apache.org/dist/spark/ and enter as the spark version
# For example:
# spark_version = 'spark-3.3.1'
spark_version = 'spark-3.3.2'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q http://www.apache.org/dist/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop3.tgz
!tar xf $SPARK_VERSION-bin-hadoop3.tgz
!pip install -q findspark

# Set Environment Variables
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop3"

# Start a SparkSession
import findspark
findspark.init()

Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Hit:4 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:7 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Hit:8 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Get:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Hit:10 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Hit:11 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal InRelease
Fetched 336 kB in 2s (171 kB/s)
Reading package lists... Done

# Import Dependencies

In [2]:
# Import packages
from pyspark.sql import SparkSession
from pyspark.sql import Row
from pyspark.sql.types import StructType, StructField, StringType, DateType, IntegerType
from pyspark import SparkFiles

# Create a SparkSession
spark = SparkSession.builder.appName("TempViews").getOrCreate()

In [3]:
url = 'https://project-4-nba.s3.amazonaws.com/2022_2023_NBA_Player_Stats_Transformed.csv'

url2 = 'https://nba2021data.s3.amazonaws.com/2021_2022_NBA_Player_Stats_Transformed.csv'

In [4]:
 # SparkFiles will allow you to resolves paths to files added through `SparkContext.addFile`

spark.sparkContext.addFile(url)

spark.sparkContext.addFile(url2)

data2 = spark.read.option('header', 'true').option("encoding", "utf-8").csv(SparkFiles.get("2022_2023_NBA_Player_Stats_Transformed.csv"), inferSchema=True, sep=',')

data3 = spark.read.option('header', 'true').option("encoding", "utf-8").csv(SparkFiles.get("2021_2022_NBA_Player_Stats_Transformed.csv"), inferSchema=True, sep=';')


# Show DataFrame
data2.show()

+---+--------------------+---+---+---+---+---+----+----+----+-----+---+---+-----+----+----+-----+-----+---+----+-----+---+---+----+---+---+---+---+---+----+
| Rk|              Player|Pos|Age| Tm|  G| GS|  MP|  FG| FGA|  FG%| 3P|3PA|  3P%|  2P| 2PA|  2P%| eFG%| FT| FTA|  FT%|ORB|DRB| TRB|AST|STL|BLK|TOV| PF| PTS|
+---+--------------------+---+---+---+---+---+----+----+----+-----+---+---+-----+----+----+-----+-----+---+----+-----+---+---+----+---+---+---+---+---+----+
|  1|    Precious Achiuwa|  C| 23|TOR| 55| 12|20.7| 3.6| 7.3|0.485|0.5|2.0|0.269| 3.0| 5.4|0.564|0.521|1.6| 2.3|0.702|1.8|4.1| 6.0|0.9|0.6|0.5|1.1|1.9| 9.2|
|  2|        Steven Adams|  C| 29|MEM| 42| 42|27.0| 3.7| 6.3|0.597|0.0|0.0|  0.0| 3.7| 6.2|0.599|0.597|1.1| 3.1|0.364|5.1|6.5|11.5|2.3|0.9|1.1|1.9|2.3| 8.6|
|  3|         Bam Adebayo|  C| 25|MIA| 75| 75|34.6| 8.0|14.9| 0.54|0.0|0.2|0.083| 8.0|14.7|0.545|0.541|4.3| 5.4|0.806|2.5|6.7| 9.2|3.2|1.2|0.8|2.5|2.8|20.4|
|  4|        Ochai Agbaji| SG| 22|UTA| 59| 22|20.5| 2.8| 6.5|0.427|1.4|3.9|0.355| 1.4| 2.7|0.532|0.532|0.9| 1.2|0.812|0.7|1.3| 2.1|1.1|0.3|0.3|0.7|1.7| 7.9|
|  5|        Santi Aldama| PF| 22|MEM| 77| 20|21.8| 3.2| 6.8| 0.47|1.2|3.5|0.353| 2.0| 3.4|0.591| 0.56|1.4| 1.9| 0.75|1.1|3.7| 4.8|1.3|0.6|0.6|0.8|1.9| 9.0|
|  6|Nickeil Alexander...| SG| 24|TOT| 59|  3|15.0| 2.2| 5.0|0.444|1.0|2.7|0.384| 1.2| 2.3|0.515|0.547|0.7| 1.0|0.667|0.3|1.5| 1.7|1.8|0.5|0.4|0.9|1.5| 6.2|
|  6|Nickeil Alexander...| SG| 24|UTA| 36|  3|14.7| 2.3| 4.7|0.488|1.0|2.4|0.402| 1.3| 2.3|0.578|0.591|0.8| 1.1|0.692|0.2|1.4| 1.6|2.1|0.7|0.4|1.3|1.6| 6.3|
|  6|Nickeil Alexander...| SG| 24|MIN| 23|  0|15.5| 2.1| 5.4|0.384|1.1|3.1|0.361| 1.0| 2.3|0.415|0.488|0.6| 0.9|0.619|0.3|1.5| 1.8|1.4|0.3|0.3|0.4|1.3| 5.9|
|  7|       Grayson Allen| SG| 27|MIL| 72| 70|27.4| 3.4| 7.7| 0.44|2.0|5.1|0.399| 1.4| 2.7|0.518|0.571|1.6| 1.8|0.905|0.8|2.4| 3.3|2.3|0.9|0.2|1.0|1.6|10.4|
|  8|       Jarrett Allen|  C| 24|CLE| 68| 68|32.6| 5.9| 9.2|0.644|0.0|0.1|  0.1| 5.9| 9.1|0.653|0.645|2.4| 3.3|0.733|3.3|6.5| 9.8|1.7|0.8|1.2|1.4|2.3|14.3|
|  9|       Jose Alvarado| PG| 24|NOP| 61| 10|21.5| 3.3| 8.0|0.411|1.4|4.0|0.336| 1.9| 4.0|0.488|0.496|1.1| 1.3|0.813|0.5|1.9| 2.3|3.0|1.1|0.2|1.3|2.0| 9.0|
| 10|       Kyle Anderson| PF| 29|MIN| 69| 46|28.4| 3.7| 7.2|0.509|0.6|1.5| 0.41| 3.0| 5.7|0.536|0.553|1.4| 2.0|0.735|1.0|4.4| 5.3|4.9|1.1|0.9|1.5|2.1| 9.4|
| 11|Giannis Antetokou...| PF| 28|MIL| 63| 63|32.1|11.2|20.3|0.553|0.7|2.7|0.275|10.5|17.6|0.596|0.572|7.9|12.3|0.645|2.2|9.6|11.8|5.7|0.8|0.8|3.9|3.1|31.1|
| 12|Thanasis Antetoko...| SF| 30|MIL| 37|  0| 5.6| 0.5| 1.2|0.435|0.0|0.2|  0.0| 0.5| 1.0|0.526|0.435|0.3| 0.6|  0.5|0.4|0.8| 1.2|0.4|0.1|0.1|0.3|0.6| 1.4|
| 13|        Cole Anthony| PG| 22|ORL| 60|  4|25.9| 4.6|10.2|0.454|1.3|3.4|0.364| 3.4| 6.7|  0.5|0.516|2.5| 2.8|0.894|0.8|4.0| 4.8|3.9|0.6|0.5|1.5|2.6|13.0|
| 14|          OG Anunoby| SF| 25|TOR| 67| 67|35.6| 6.3|13.2|0.476|2.1|5.5|0.387| 4.2| 7.7|0.539|0.556|2.1| 2.5|0.838|1.4|3.5| 5.0|2.0|1.9|0.7|2.0|3.0|16.8|
| 15|    Ryan Arcidiacono| PG| 28|TOT| 20|  4| 8.6| 0.5| 1.9|0.243|0.4|1.2|0.348| 0.1| 0.7|0.071|0.351|0.0| 0.0|  0.0|0.0|0.8| 0.8|1.2|0.3|0.0|0.4|0.9| 1.3|
| 15|    Ryan Arcidiacono| PG| 28|NYK| 11|  0| 2.4| 0.1| 0.5|  0.2|0.1|0.3|0.333| 0.0| 0.2|  0.0|  0.3|0.0| 0.0|  0.0|0.0|0.4| 0.4|0.2|0.2|0.0|0.1|0.3| 0.3|
| 15|    Ryan Arcidiacono| PG| 28|POR|  9|  4|16.2| 0.9| 3.6| 0.25|0.8|2.2| 0.35| 0.1| 1.3|0.083|0.359|0.0| 0.0|  0.0|0.0|1.2| 1.2|2.3|0.3|0.0|0.7|1.6| 2.6|
| 16|         Deni Avdija| SF| 22|WAS| 76| 40|26.6| 3.3| 7.6|0.437|0.9|3.1|0.297| 2.4| 4.6| 0.53|0.497|1.6| 2.2|0.739|1.0|5.4| 6.4|2.8|0.9|0.4|1.6|2.8| 9.2|
+---+--------------------+---+---+---+---+---+----+----+----+-----+---+---+-----+----+----+-----+-----+---+----+-----+---+---+----+---+---+---+---+---+----+
only showing top 20 rows

In [ ]:
data3.show()

+---+--------------------+---+---+---+---+---+----+----+----+-----+---+---+-----+---+----+-----+-----+---+----+-----+---+---+----+---+---+---+---+---+----+
| Rk|              Player|Pos|Age| Tm|  G| GS|  MP|  FG| FGA|  FG%| 3P|3PA|  3P%| 2P| 2PA|  2P%| eFG%| FT| FTA|  FT%|ORB|DRB| TRB|AST|STL|BLK|TOV| PF| PTS|
+---+--------------------+---+---+---+---+---+----+----+----+-----+---+---+-----+---+----+-----+-----+---+----+-----+---+---+----+---+---+---+---+---+----+
|  1|    Precious Achiuwa|  C| 22|TOR| 73| 28|23.6| 3.6| 8.3|0.439|0.8|2.1|0.359|2.9| 6.1|0.468|0.486|1.1| 1.8|0.595|2.0|4.5| 6.5|1.1|0.5|0.6|1.2|2.1| 9.1|
|  2|        Steven Adams|  C| 28|MEM| 76| 75|26.3| 2.8| 5.1|0.547|0.0|0.0|  0.0|2.8| 5.0|0.548|0.547|1.4| 2.6|0.543|4.6|5.4|10.0|3.4|0.9|0.8|1.5|2.0| 6.9|
|  3|         Bam Adebayo|  C| 24|MIA| 56| 56|32.6| 7.3|13.0|0.557|0.0|0.1|  0.0|7.3|12.9|0.562|0.557|4.6| 6.1|0.753|2.4|7.6|10.1|3.4|1.4|0.8|2.6|3.1|19.1|
|  4|        Santi Aldama| PF| 21|MEM| 32|  0|11.3| 1.7| 4.1|0.402|0.2|1.5|0.125|1.5| 2.6| 0.56|0.424|0.6| 1.0|0.625|1.0|1.7| 2.7|0.7|0.2|0.3|0.5|1.1| 4.1|
|  5|   LaMarcus Aldridge|  C| 36|BRK| 47| 12|22.3| 5.4| 9.7| 0.55|0.3|1.0|0.304|5.1| 8.8|0.578|0.566|1.9| 2.2|0.873|1.6|3.9| 5.5|0.9|0.3|1.0|0.9|1.7|12.9|
|  6|Nickeil Alexander...| SG| 23|TOT| 65| 21|22.6| 3.9|10.5|0.372|1.6|5.2|0.311|2.3| 5.3|0.433|0.449|1.2| 1.7|0.743|0.6|2.3| 2.9|2.4|0.7|0.4|1.4|1.6|10.6|
|  6|Nickeil Alexander...| SG| 23|NOP| 50| 19|26.3| 4.7|12.6|0.375|1.9|6.1|0.311|2.8| 6.5|0.434| 0.45|1.4| 1.9|0.722|0.7|2.6| 3.3|2.8|0.8|0.4|1.7|1.8|12.8|
|  6|Nickeil Alexander...| SG| 23|UTA| 15|  2| 9.9| 1.1| 3.2|0.333|0.7|2.2|0.303|0.4| 1.0|  0.4|0.438|0.7| 0.8|0.917|0.1|1.5| 1.5|1.1|0.3|0.3|0.5|1.0| 3.5|
|  7|       Grayson Allen| SG| 26|MIL| 66| 61|27.3| 3.9| 8.6|0.448|2.4|5.9|0.409|1.5| 2.7|0.533|0.588|1.0| 1.1|0.865|0.5|2.9| 3.4|1.5|0.7|0.3|0.7|1.5|11.1|
|  8|       Jarrett Allen|  C| 23|CLE| 56| 56|32.3| 6.6| 9.7|0.677|0.0|0.2|  0.1|6.6| 9.6|0.688|0.678|2.9| 4.2|0.708|3.4|7.3|10.8|1.6|0.8|1.3|1.7|1.7|16.1|
|  9|       Jose Alvarado| PG| 23|NOP| 54|  1|15.4| 2.4| 5.4|0.446|0.6|2.0|0.291|1.8| 3.4|0.538|  0.5|0.7| 1.0|0.679|0.5|1.4| 1.9|2.8|1.3|0.1|0.7|1.4| 6.1|
| 10|     Justin Anderson| SF| 28|TOT| 16|  6|19.8| 2.3| 5.9|0.379|0.9|3.7|0.254|1.3| 2.3|0.583|0.458|0.9| 1.2|0.789|0.3|2.6| 2.9|2.1|0.5|0.4|0.5|1.4| 6.4|
| 10|     Justin Anderson| SF| 28|CLE|  3|  0|15.7| 1.3| 2.7|  0.5|0.7|2.0|0.333|0.7| 0.7|  1.0|0.625|1.0| 1.3| 0.75|0.0|2.0| 2.0|2.0|0.3|0.0|0.7|1.3| 4.3|
| 10|     Justin Anderson| SF| 28|IND| 13|  6|20.7| 2.5| 6.7|0.368|1.0|4.1|0.245|1.5| 2.6|0.559|0.443|0.9| 1.2|  0.8|0.3|2.8| 3.1|2.1|0.5|0.5|0.5|1.4| 6.8|
| 11|       Kyle Anderson| PF| 28|MEM| 69| 11|21.5| 3.0| 6.8|0.446|0.5|1.6| 0.33|2.5| 5.2|0.481|0.484|1.0| 1.5|0.638|1.0|4.3| 5.3|2.7|1.1|0.7|1.0|1.6| 7.6|
| 12|Giannis Antetokou...| PF| 27|MIL| 67| 67|32.9|10.3|18.6|0.553|1.1|3.6|0.293|9.2|15.0|0.616|0.582|8.3|11.4|0.722|2.0|9.6|11.6|5.8|1.1|1.4|3.3|3.2|29.9|
| 13|Thanasis Antetoko...| SF| 29|MIL| 48|  6| 9.9| 1.5| 2.7|0.547|0.0|0.3|0.143|1.4| 2.4|0.596|0.555|0.6| 1.0| 0.63|0.8|1.3| 2.1|0.5|0.3|0.3|0.5|1.4| 3.6|
| 14|     Carmelo Anthony| PF| 37|LAL| 69|  3|26.0| 4.6|10.5|0.441|2.2|5.8|0.375|2.5| 4.7|0.521|0.544|1.9| 2.3| 0.83|0.9|3.3| 4.2|1.0|0.7|0.8|0.9|2.4|13.3|
| 15|        Cole Anthony| PG| 21|ORL| 65| 65|31.7| 5.5|14.0|0.391|2.0|6.0|0.338|3.5| 8.0|0.432|0.464|3.3| 3.9|0.854|0.5|4.9| 5.4|5.7|0.7|0.3|2.6|2.6|16.3|
| 16|          OG Anunoby| SF| 24|TOR| 48| 48|36.0| 6.4|14.5|0.443|2.4|6.6|0.363|4.0| 7.9|0.511|0.526|1.9| 2.5|0.754|1.5|4.0| 5.5|2.6|1.5|0.5|1.7|2.7|17.1|
+---+--------------------+---+---+---+---+---+----+----+----+-----+---+---+-----+---+----+-----+-----+---+----+-----+---+---+----+---+---+---+---+---+----+
only showing top 20 rows

In [7]:
# Convert df to pandas
pandas_df = data2.toPandas()
pandas2_df = data3.toPandas()

In [8]:
# display head of first dataframe
pandas_df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,C,23,TOR,55,12,20.7,3.6,7.3,...,0.702,1.8,4.1,6.0,0.9,0.6,0.5,1.1,1.9,9.2
1,2,Steven Adams,C,29,MEM,42,42,27.0,3.7,6.3,...,0.364,5.1,6.5,11.5,2.3,0.9,1.1,1.9,2.3,8.6
2,3,Bam Adebayo,C,25,MIA,75,75,34.6,8.0,14.9,...,0.806,2.5,6.7,9.2,3.2,1.2,0.8,2.5,2.8,20.4
3,4,Ochai Agbaji,SG,22,UTA,59,22,20.5,2.8,6.5,...,0.812,0.7,1.3,2.1,1.1,0.3,0.3,0.7,1.7,7.9
4,5,Santi Aldama,PF,22,MEM,77,20,21.8,3.2,6.8,...,0.750,1.1,3.7,4.8,1.3,0.6,0.6,0.8,1.9,9.0

In [9]:
# display head of second dataframe
pandas2_df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,C,22,TOR,73,28,23.6,3.6,8.3,...,0.595,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1
1,2,Steven Adams,C,28,MEM,76,75,26.3,2.8,5.1,...,0.543,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9
2,3,Bam Adebayo,C,24,MIA,56,56,32.6,7.3,13.0,...,0.753,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1
3,4,Santi Aldama,PF,21,MEM,32,0,11.3,1.7,4.1,...,0.625,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1
4,5,LaMarcus Aldridge,C,36,BRK,47,12,22.3,5.4,9.7,...,0.873,1.6,3.9,5.5,0.9,0.3,1.0,0.9,1.7,12.9

In [10]:
# Rename Age and Player Columns second dataframe
pandas2_df = pandas2_df.rename(columns = {' Age': 'Age'})

pandas2_df = pandas2_df.rename(columns = {'Player ': 'Player'})

In [27]:
# Merge both dataframe using outer join
joined_data = pandas_df.merge(pandas2_df, on='Player', how='outer')

In [28]:
# Check for missing values
joined_data.isna().sum()

Rk_x      269
Player      0
Pos_x     269
Age_x     269
Tm_x      269
G_x       269
GS_x      269
MP_x      269
FG_x      269
FGA_x     269
FG%_x     269
3P_x      269
3PA_x     269
3P%_x     269
2P_x      269
2PA_x     269
2P%_x     269
eFG%_x    269
FT_x      269
FTA_x     269
FT%_x     269
ORB_x     269
DRB_x     269
TRB_x     269
AST_x     269
STL_x     269
BLK_x     269
TOV_x     269
PF_x      269
PTS_x     269
Rk_y      127
Pos_y     127
Age_y     127
Tm_y      127
G_y       127
GS_y      127
MP_y      127
FG_y      127
FGA_y     127
FG%_y     127
3P_y      127
3PA_y     127
3P%_y     127
2P_y      127
2PA_y     127
2P%_y     127
eFG%_y    127
FT_y      127
FTA_y     127
FT%_y     127
ORB_y     127
DRB_y     127
TRB_y     127
AST_y     127
STL_y     127
BLK_y     127
TOV_y     127
PF_y      127
PTS_y     127
dtype: int64

In [29]:
# Drop missing values
joined_data = joined_data.dropna()

In [30]:
type(joined_data)

pandas.core.frame.DataFrame

In [33]:
# Check missing values are removed
joined_data.isna().sum()

Rk_x      0
Player    0
Pos_x     0
Age_x     0
Tm_x      0
G_x       0
GS_x      0
MP_x      0
FG_x      0
FGA_x     0
FG%_x     0
3P_x      0
3PA_x     0
3P%_x     0
2P_x      0
2PA_x     0
2P%_x     0
eFG%_x    0
FT_x      0
FTA_x     0
FT%_x     0
ORB_x     0
DRB_x     0
TRB_x     0
AST_x     0
STL_x     0
BLK_x     0
TOV_x     0
PF_x      0
PTS_x     0
Rk_y      0
Pos_y     0
Age_y     0
Tm_y      0
G_y       0
GS_y      0
MP_y      0
FG_y      0
FGA_y     0
FG%_y     0
3P_y      0
3PA_y     0
3P%_y     0
2P_y      0
2PA_y     0
2P%_y     0
eFG%_y    0
FT_y      0
FTA_y     0
FT%_y     0
ORB_y     0
DRB_y     0
TRB_y     0
AST_y     0
STL_y     0
BLK_y     0
TOV_y     0
PF_y      0
PTS_y     0
dtype: int64

In [34]:
# shape of the dataset
joined_data.shape

(707, 59)

# Import dependencies

In [43]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from pyspark.sql.functions import col
import numpy as np
import seaborn as sns

In [ ]:
# visualize the relationship between the features and the response using scatterplots
sns.pairplot(data, x_vars=['TV','Radio','Newspaper'], y_vars='Sales', size=7, aspect=0.7)

In [ ]:
# Select the features (X) and target variables (y) for points (PTS) and assists (AST)
features = joined_data[['Age_x', 'G_x', 'GS_x', 'MP_x', 'FG_x', 'FGA_x',
                       'Age_y', 'G_y', 'GS_y', 'MP_y', 'FG_y', 'FGA_y']]

target_pts = joined_data[['PTS_x']]

target_ast = joined_data[['AST_x']]

In [64]:
# Split the data into training and test sets
X_train, X_test, y_train_pts, y_test_pts, y_train_ast, y_test_ast = train_test_split(features, target_pts, target_ast, test_size=0.4, random_state=42)

# Data Transformations

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
# Make a copy of Dataset
joined_data_copy = joined_data.copy()

In [37]:
# Drop player column
joined_data_copy = joined_data_copy.drop('Player', axis =1)
joined_data_copy

,Rk_x,Pos_x,Age_x,Tm_x,G_x,GS_x,MP_x,FG_x,FGA_x,FG%_x,...,FT%_y,ORB_y,DRB_y,TRB_y,AST_y,STL_y,BLK_y,TOV_y,PF_y,PTS_y
0,1.0,C,23.0,TOR,55.0,12.0,20.7,3.6,7.3,0.485,...,0.595,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1
1,2.0,C,29.0,MEM,42.0,42.0,27.0,3.7,6.3,0.597,...,0.543,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9
2,3.0,C,25.0,MIA,75.0,75.0,34.6,8.0,14.9,0.540,...,0.753,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1
4,5.0,PF,22.0,MEM,77.0,20.0,21.8,3.2,6.8,0.470,...,0.625,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1
5,6.0,SG,24.0,TOT,59.0,3.0,15.0,2.2,5.0,0.444,...,0.743,0.6,2.3,2.9,2.4,0.7,0.4,1.4,1.6,10.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829,535.0,PF,34.0,TOR,54.0,9.0,14.7,2.0,3.7,0.545,...,0.481,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3
830,536.0,PG,24.0,ATL,73.0,73.0,34.8,8.2,19.0,0.429,...,0.904,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4
831,537.0,C,24.0,MIA,9.0,0.0,9.2,1.8,3.0,0.593,...,0.623,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3
832,538.0,C,30.0,MIA,15.0,2.0,14.5,2.5,3.9,0.627,...,0.776,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2
833,539.0,C,25.0,LAC,76.0,76.0,28.6,4.3,6.8,0.634,...,0.727,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3

In [38]:
#CHeck types of Data
joined_data_copy.dtypes

Rk_x      float64
Pos_x      object
Age_x     float64
Tm_x       object
G_x       float64
GS_x      float64
MP_x      float64
FG_x      float64
FGA_x     float64
FG%_x     float64
3P_x      float64
3PA_x     float64
3P%_x     float64
2P_x      float64
2PA_x     float64
2P%_x     float64
eFG%_x    float64
FT_x      float64
FTA_x     float64
FT%_x     float64
ORB_x     float64
DRB_x     float64
TRB_x     float64
AST_x     float64
STL_x     float64
BLK_x     float64
TOV_x     float64
PF_x      float64
PTS_x     float64
Rk_y      float64
Pos_y      object
Age_y     float64
Tm_y       object
G_y       float64
GS_y      float64
MP_y      float64
FG_y      float64
FGA_y     float64
FG%_y     float64
3P_y      float64
3PA_y     float64
3P%_y     float64
2P_y      float64
2PA_y     float64
2P%_y     float64
eFG%_y    float64
FT_y      float64
FTA_y     float64
FT%_y     float64
ORB_y     float64
DRB_y     float64
TRB_y     float64
AST_y     float64
STL_y     float64
BLK_y     float64
TOV_y     float64
PF_y      float64
PTS_y     float64
dtype: object

In [39]:
# Scale only numeric dataset
numerical = joined_data_copy.select_dtypes(include='float64').columns
joined_data_copy.loc[:,numerical]= StandardScaler().fit_transform(joined_data_copy.loc[:,numerical])

In [40]:
# Create a copy of transformed data
joined_data_copy2 = joined_data_copy.copy()

In [41]:
# Drop Position and team columns
joined_data_copy = joined_data_copy.drop(["Pos_x","Tm_x","Pos_y","Tm_y"], axis=1)
joined_data_copy.shape

(707, 54)

In [44]:
# Transform the Position and Team column using get_dummies()
dummies = pd.get_dummies(joined_data_copy2[["Pos_x","Tm_x","Pos_y","Tm_y"]])
# Display sample data
dummies.head()

,Pos_x_C,Pos_x_PF,Pos_x_PF-SF,Pos_x_PG,Pos_x_SF,Pos_x_SF-SG,Pos_x_SG,Tm_x_ATL,Tm_x_BOS,Tm_x_BRK,...,Tm_y_ORL,Tm_y_PHI,Tm_y_PHO,Tm_y_POR,Tm_y_SAC,Tm_y_SAS,Tm_y_TOR,Tm_y_TOT,Tm_y_UTA,Tm_y_WAS
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [55]:
# Concatenate the df_shopping_transformed and the card_dummies DataFrames
df_transformed = pd.concat([joined_data_copy, dummies], axis=1)

# Display sample data
df_transformed.head()

,Rk_x,Age_x,G_x,GS_x,MP_x,FG_x,FGA_x,FG%_x,3P_x,3PA_x,...,Tm_y_ORL,Tm_y_PHI,Tm_y_PHO,Tm_y_POR,Tm_y_SAC,Tm_y_SAS,Tm_y_TOR,Tm_y_TOT,Tm_y_UTA,Tm_y_WAS
0,-1.701992,-0.932663,0.388807,-0.339998,0.068807,0.111156,0.043808,0.106000,-0.624853,-0.396785,...,0,0,0,0,0,0,1,0,0,0
1,-1.695279,0.513374,-0.154860,0.815113,0.749709,0.154502,-0.166889,1.086783,-1.192244,-1.282845,...,0,0,0,0,0,0,0,0,0,0
2,-1.688567,-0.450651,1.225219,2.085736,1.571114,2.018403,1.645111,0.587635,-1.192244,-1.194239,...,0,0,0,0,0,0,0,0,0,0
4,-1.675142,-1.173670,1.308861,-0.031968,0.187695,-0.062230,-0.061540,-0.025354,0.169495,0.267761,...,0,0,0,0,0,0,0,0,0,0
5,-1.668430,-0.691657,0.556090,-0.686532,-0.547247,-0.495695,-0.440796,-0.253036,-0.057461,-0.086663,...,0,0,0,0,0,0,0,1,0,0

In [56]:
# define the features (X)
features = df_transformed.drop(['PTS_x'], axis =1)

In [58]:
# Define target vector
target_pts = df_transformed['PTS_x'].values.reshape(-1, 1)

In [61]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(features, target_pts, random_state=42)

In [62]:
# Create the regression instance
model_pts = LinearRegression()

# Fitting the model
model_pts.fit(X_train, y_train_pts)

LinearRegression()

In [63]:
# Make predictions for points
pts_predictions = model_pts.predict(X_test)

# Model Accuracy

In [64]:
# Model Accuracy for Points
print('Test Acc: %.3f' % model_pts.score(X_test, y_test))
# MSE
print('MSE: %.3f' %np.sqrt(metrics.mean_squared_error(y_test, pts_predictions)))

Test Acc: 1.000
MSE: 0.013

 Note that rsquare of 1 might be because of overfitting

# Feature Importances

In [71]:
# Create the Random Forest Regressor
rf_model = RandomForestRegressor()

# Fit the model to the training data for points
rf_model.fit(X_train, y_train)

# Use Random Forests in sklearn to automatically calculate feature importance
importances = rf_model.feature_importances_

# Sort the features by their importance
sorted(zip(rf_model.feature_importances_, features.columns), reverse=False)

<ipython-input-71-fe43094b23c2>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train, y_train)

[(0.0, 'Pos_y_PF-SF'),
 (0.0, 'Pos_y_PG-SG'),
 (0.0, 'Pos_y_SF-SG'),
 (2.918549578583325e-20, 'Pos_y_C-PF'),
 (4.156440242132827e-09, 'Pos_x_SF-SG'),
 (1.29169835338862e-08, 'Pos_y_SG-PG'),
 (2.3022055273649492e-08, 'Pos_x_PF-SF'),
 (4.9817406660332565e-08, 'Tm_y_CHI'),
 (6.936402226747293e-08, 'Pos_y_SG-SF'),
 (1.2839187457403e-07, 'Tm_y_SAC'),
 (2.7222142704211837e-07, 'Tm_x_NOP'),
 (3.3373459752131157e-07, 'Tm_y_ATL'),
 (3.7138822374251036e-07, 'Tm_y_BOS'),
 (4.871768317206774e-07, 'Tm_x_DEN'),
 (4.874832936077324e-07, 'Tm_y_PHI'),
 (5.132871680962655e-07, 'Tm_y_DEN'),
 (5.239973784924642e-07, 'Tm_y_NYK'),
 (5.702743389895093e-07, 'Tm_y_IND'),
 (6.068071405174868e-07, 'Tm_x_MIN'),
 (6.236113688833637e-07, 'Tm_y_TOR'),
 (6.476440543394758e-07, 'Tm_y_PHO'),
 (6.867954764345874e-07, 'Tm_y_CLE'),
 (1.0125358347501102e-06, 'Tm_y_MIL'),
 (1.1141781340947459e-06, 'Tm_x_BRK'),
 (1.1720672230015602e-06, 'Tm_y_LAL'),
 (1.2028807978229644e-06, 'Tm_y_ORL'),
 (1.2486203695264594e-06, 'Tm_x_PHO'),
 (1.2491310137009244e-06, 'Tm_x_MIA'),
 (1.2689725455786458e-06, 'Tm_x_CLE'),
 (1.2944803706928035e-06, 'Tm_x_MEM'),
 (1.3280545897762038e-06, 'Tm_y_MIN'),
 (1.403634643841298e-06, 'Tm_x_ATL'),
 (1.5369246326788641e-06, 'Tm_x_OKC'),
 (1.6740419879854933e-06, 'Tm_y_POR'),
 (1.6839542104965248e-06, 'Tm_y_OKC'),
 (1.7044614623938954e-06, 'Tm_x_LAC'),
 (1.839528202651216e-06, 'Tm_x_BOS'),
 (1.841968440949187e-06, 'Tm_y_TOT'),
 (2.195105684285736e-06, 'Tm_x_DAL'),
 (2.1995083474362027e-06, 'Tm_y_LAC'),
 (2.2191002823600166e-06, 'Tm_x_DET'),
 (2.2688553840736325e-06, 'Tm_x_CHI'),
 (2.2966079410052385e-06, 'Tm_y_MEM'),
 (2.3673460773810458e-06, 'Tm_x_ORL'),
 (2.4180560230417126e-06, 'Tm_x_HOU'),
 (2.7692558109429123e-06, 'Tm_x_IND'),
 (2.959860313460781e-06, 'Tm_x_MIL'),
 (3.000576974142819e-06, 'Tm_y_CHO'),
 (3.0510746849095164e-06, 'Tm_x_SAC'),
 (3.0916773079762406e-06, 'Tm_x_UTA'),
 (4.277784963505361e-06, 'Tm_y_HOU'),
 (4.637684222858624e-06, 'Tm_x_CHO'),
 (4.763933632701386e-06, 'Tm_y_SAS'),
 (4.987879824852611e-06, 'Tm_x_SAS'),
 (5.742332862481466e-06, 'Tm_x_POR'),
 (5.8453611274322385e-06, 'Tm_y_DET'),
 (5.947888519340221e-06, 'Tm_x_TOR'),
 (6.089273916785515e-06, 'Tm_y_NOP'),
 (6.1773162489365506e-06, 'Tm_x_NYK'),
 (6.2543084589657255e-06, 'Tm_x_GSW'),
 (7.00896298306776e-06, 'Tm_x_TOT'),
 (7.056504858170075e-06, 'Tm_x_LAL'),
 (7.1445536196642294e-06, 'Tm_y_DAL'),
 (7.256307088858655e-06, 'Tm_y_UTA'),
 (7.410956965041808e-06, 'Pos_y_C'),
 (8.419997168655265e-06, 'Tm_y_MIA'),
 (9.752572713244146e-06, 'Tm_y_BRK'),
 (1.012120620833405e-05, 'Pos_y_SG'),
 (1.0808170366273632e-05, 'Pos_x_PF'),
 (1.0949245405640643e-05, 'Pos_y_PF'),
 (1.194170589921115e-05, 'Tm_y_WAS'),
 (1.2860320204947827e-05, 'Pos_x_SF'),
 (1.628030512708728e-05, 'Tm_y_GSW'),
 (1.688971828548049e-05, 'Pos_y_PG'),
 (1.984372591869586e-05, 'Pos_x_C'),
 (2.0259197512672234e-05, 'Pos_y_SF'),
 (2.2356496913346358e-05, 'Pos_x_PG'),
 (2.994808205235291e-05, 'Pos_x_SG'),
 (3.2060081399000104e-05, 'Tm_x_WAS'),
 (3.541713673931223e-05, 'Tm_x_PHI'),
 (5.188859287613316e-05, 'BLK_y'),
 (6.301942446942131e-05, 'STL_y'),
 (7.544056045734649e-05, 'Age_y'),
 (7.808591639852932e-05, 'G_y'),
 (8.059507545331742e-05, 'GS_y'),
 (8.547632369286265e-05, 'FG_y'),
 (9.377059922969239e-05, 'DRB_y'),
 (9.670850258031739e-05, 'PF_y'),
 (0.00010190556165100196, 'STL_x'),
 (0.0001019505832596695, 'AST_y'),
 (0.00010269151389270607, '2PA_y'),
 (0.00010360759631603756, 'TRB_y'),
 (0.00011123418195724513, 'ORB_y'),
 (0.0001178812783126886, 'GS_x'),
 (0.00012017259658501816, 'MP_y'),
 (0.00012400967846934707, 'eFG%_y'),
 (0.00012755241892713787, 'FG%_y'),
 (0.00013656051962911432, '2P_y'),
 (0.00014589863238484457, 'DRB_x'),
 (0.0001617568278085483, 'BLK_x'),
 (0.00016927108426018626, '2P%_y'),
 (0.00017922597368803225, 'Age_x'),
 (0.00018040763578269832, 'G_x'),
 (0.00018060745969617986, 'FTA_y'),
 (0.00018525938495567897, 'TOV_y'),
 (0.000191248280342288, 'TRB_x'),
 (0.00019614435421817377, 'AST_x'),
 (0.0001972437568965414, 'Rk_x'),
 (0.00020720685352327442, '3P%_y'),
 (0.00022778906842370298, 'PF_x'),
 (0.00022794649314013675, 'Rk_y'),
 (0.00022971048946060035, '2PA_x'),
 (0.0002462586089932191, 'FT%_y'),
 (0.00024677221179383293, 'TOV_x'),
 (0.0002501689100753952, 'ORB_x'),
 (0.0002553576894885912, 'eFG%_x'),
 (0.000264321633382763, 'FT_y'),
 (0.0002750270039021678, '2P%_x'),
 (0.00028914363936392867, 'FG%_x'),
 (0.0003407402832997572, '3P_y'),
 (0.0003942298707886622, '3PA_y'),
 (0.00042854162228581153, '3P%_x'),
 (0.00046839972149138843, '2P_x'),
 (0.0004887101684327002, 'FGA_y'),
 (0.000590337321198293, 'FT%_x'),
 (0.0006151933579227174, '3P_x'),
 (0.0006981689513373544, '3PA_x'),
 (0.0008085127841198625, 'MP_x'),
 (0.0015061763566546905, 'PTS_y'),
 (0.0016455671116556165, 'FTA_x'),
 (0.004830338288363893, 'FT_x'),
 (0.25737976282361447, 'FGA_x'),
 (0.7231076708625168, 'FG_x')]

# Continue From HERE : Next STEPS 
- Select features to use based on features importance
- Repeat all steps from above:
- 1. Run linear regression model again on those features
- 2. Predict and then Evaluate Model

In [67]:
# Create separate models for points and assists
model_pts = LinearRegression()

# model_ast = LinearRegression()


# Train the models
model_pts.fit(X_train, y_train_pts)

# model_ast.fit(X_train, y_train_ast)

LinearRegression()

# Model Evaluation

In [76]:
# Make predictions for points and assists
pts_predictions = model_pts.predict(X_test)

# ast_predictions = model_ast.predict(X_test)

In [88]:
# Model Accuracy for Points
print('Test Acc: %.3f' % model_pts.score(X_test, y_test_pts))
# MSE
print('MSE: %.3f' %np.sqrt(metrics.mean_squared_error(y_test_pts, pts_predictions)))

Test Acc: 0.989
MSE: 0.692

# Model Deployment

In [ ]:
# Filter only unique players
player_names = joined_data['Player'].unique()

print(player_names)

['Precious Achiuwa' 'Steven Adams' 'Bam Adebayo' 'Santi Aldama'
 'Nickeil Alexander-Walker' 'Grayson Allen' 'Jarrett Allen'
 'Jose Alvarado' 'Kyle Anderson' 'Giannis Antetokounmpo'
 'Thanasis Antetokounmpo' 'Cole Anthony' 'OG Anunoby' 'Ryan Arcidiacono'
 'Deni Avdija' 'Deandre Ayton' 'Udoka Azubuike' 'Marvin Bagley III'
 'LaMelo Ball' 'Mo Bamba' 'Desmond Bane' 'Dalano Banton' 'Harrison Barnes'
 'Scottie Barnes' 'RJ Barrett' 'Will Barton' 'Charles Bassey'
 'Keita Bates-Diop' 'Nicolas Batum' 'Darius Bazley' 'Bradley Beal'
 'Malik Beasley' 'D?vis Bert?ns' 'Patrick Beverley' 'Saddiq Bey'
 'Khem Birch' 'Goga Bitadze' 'Bismack Biyombo' 'Bogdan Bogdanovi?'
 'Bojan Bogdanovi?' 'Bol Bol' 'Leandro Bolmaro' 'Devin Booker'
 'Brandon Boston Jr.' 'Chris Boucher' 'James Bouknight' 'Tony Bradley'
 'Mikal Bridges' 'Oshae Brissett' 'Malcolm Brogdon' 'Dillon Brooks'
 'Bruce Brown' 'Greg Brown III' 'Jaylen Brown' 'Moses Brown'
 'Sterling Brown' 'Troy Brown Jr.' 'Jalen Brunson' 'Thomas Bryant'
 'Reggie Bullock' 'Alec Burks' 'Jared Butler' 'Jimmy Butler'
 'Kentavious Caldwell-Pope' 'Facundo Campazzo' 'Vlatko ?an?ar'
 'Clint Capela' 'Vernon Carey Jr.' 'Jevon Carter' 'Wendell Carter Jr.'
 'Alex Caruso' 'Justin Champagnie' 'Josh Christopher' 'Brandon Clarke'
 'Jordan Clarkson' 'Nic Claxton' 'Amir Coffey' 'John Collins'
 'Zach Collins' 'Mike Conley' 'Pat Connaughton' 'Robert Covington'
 'Torrey Craig' 'Jae Crowder' 'Jarrett Culver' 'Cade Cunningham'
 'Seth Curry' 'Stephen Curry' 'Anthony Davis' 'Terence Davis'
 'Dewayne Dedmon' 'DeMar DeRozan' 'Mamadi Diakite' 'Hamidou Diallo'
 'Gorgui Dieng' 'Spencer Dinwiddie' 'Donte DiVincenzo' 'Luka Don?i?'
 'Luguentz Dort' 'Ayo Dosunmu' 'Devon Dotson' 'Jeff Dowtin' 'PJ Dozier'
 'Goran Dragi?' 'Andre Drummond' 'Chris Duarte' 'David Duke Jr.'
 'Kris Dunn' 'Kevin Durant' 'Anthony Edwards' 'Kessler Edwards'
 'Joel Embiid' 'Drew Eubanks' 'Bruno Fernando' 'Dorian Finney-Smith'
 'Malachi Flynn' 'Bryn Forbes' 'Trent Forrest' 'Evan Fournier'
 "De'Aaron Fox" 'Markelle Fultz' 'Wenyen Gabriel' 'Daniel Gafford'
 'Darius Garland' 'Usman Garuba' 'Luka Garza' 'Rudy Gay' 'Paul George'
 'Taj Gibson' 'Josh Giddey' 'Shai Gilgeous-Alexander' 'Anthony Gill'
 'Rudy Gobert' 'Jordan Goodwin' 'Aaron Gordon' 'Eric Gordon'
 "Devonte' Graham" 'Jerami Grant' 'Danny Green' 'Draymond Green'
 'Jalen Green' 'JaMychal Green' 'Javonte Green' 'Jeff Green' 'Josh Green'
 'Blake Griffin' 'Quentin Grimes' 'Rui Hachimura' 'Tyrese Haliburton'
 'R.J. Hampton' 'Tim Hardaway Jr.' 'James Harden' 'Montrezl Harrell'
 'Gary Harris' 'Joe Harris' 'Tobias Harris' 'Shaquille Harrison'
 'Josh Hart' 'Isaiah Hartenstein' 'Udonis Haslem' 'Sam Hauser'
 'Jaxson Hayes' 'Killian Hayes' 'Gordon Hayward' 'Tyler Herro'
 'Buddy Hield' 'Haywood Highsmith' 'George Hill' 'Malcolm Hill'
 'Aaron Holiday' 'Jrue Holiday' 'Justin Holiday' 'Richaun Holmes'
 'Al Horford' 'Talen Horton-Tucker' 'Danuel House Jr.' 'Kevin Huerter'
 'Jay Huff' "De'Andre Hunter" 'Bones Hyland' 'Serge Ibaka'
 'Andre Iguodala' 'Joe Ingles' 'Brandon Ingram' 'Kyrie Irving'
 'Frank Jackson' 'Isaiah Jackson' 'Jaren Jackson Jr.' 'Justin Jackson'
 'Reggie Jackson' 'LeBron James' 'Ty Jerome' 'Isaiah Joe' 'Alize Johnson'
 'Cameron Johnson' 'Jalen Johnson' 'James Johnson' 'Keldon Johnson'
 'Keon Johnson' 'Stanley Johnson' 'Nikola Joki?' 'Carlik Jones'
 'Damian Jones' 'Derrick Jones Jr.' 'Herbert Jones' 'Kai Jones'
 'Tre Jones' 'Tyus Jones' 'DeAndre Jordan' 'Cory Joseph' 'Frank Kaminsky'
 'Luke Kennard' 'Braxton Key' 'Louis King' 'Corey Kispert' 'Maxi Kleber'
 'Nathan Knight' 'Kevin Knox' 'John Konchar' 'Furkan Korkmaz'
 'Luke Kornet' 'Vit Krejci' 'Jonathan Kuminga' 'Kyle Kuzma' 'Anthony Lamb'
 'Jock Landale' 'Romeo Langford' 'Zach LaVine' 'Damion Lee' 'Saben Lee'
 'Alex Len' 'Caris LeVert' 'Kira Lewis Jr.' 'Damian Lillard'
 'Nassir Little' 'Isaiah Livers' 'Kevon Looney' 'Brook Lopez'
 'Robin Lopez' 'Kevin Love' 'Kyle Lowry' 'Trey Lyles'
 'Sandro Mamukelashvili' 'Terance Mann' 'Tre Mann' 'Boban Marjanovi?'
 'Lauri Markkanen' 'Naji Marshall' 'Caleb Martin' 'Cody Martin'
 'Kenyon Martin Jr.' 'Garrison Mathews' 'Wesley Matthews' 'Tyrese Maxey'
 'Skylar Mays' 'Miles McBride' 'Mac McClung' 'CJ McCollum'
 'T.J. McConnell' 'Jaden McDaniels' 'Jalen McDaniels' 'Doug McDermott'
 'JaVale McGee' 'Rodney McGruder' 'Jordan McLaughlin' "De'Anthony Melton"
 'Sam Merrill' 'Chimezie Metu' 'Khris Middleton' 'Patty Mills'
 'Shake Milton' 'Davion Mitchell' 'Donovan Mitchell' 'Evan Mobley'
 'Malik Monk' 'Moses Moody' 'Xavier Moon' 'Ja Morant' 'Marcus Morris'
 'Markieff Morris' 'Monte Morris' 'Trey Murphy III' 'Dejounte Murray'
 'Mike Muscala' 'Svi Mykhailiuk' 'Larry Nance Jr.' 'Aaron Nesmith'
 'Raul Neto' 'Georges Niang' 'Daishen Nix' 'Zeke Nnaji' 'Nerlens Noel'
 'Jaylen Nowell' 'Frank Ntilikina' 'Jusuf Nurki?' 'Jordan Nwora'
 "Royce O'Neale" 'Chuma Okeke' 'Josh Okogie' 'Onyeka Okongwu'
 'Isaac Okoro' 'KZ Okpala' 'Victor Oladipo' 'Kelly Olynyk'
 'Eugene Omoruyi' 'Cedi Osman' 'Kelly Oubre Jr.' 'Chris Paul'
 'Cameron Payne' 'Gary Payton II' 'Theo Pinson' 'Mason Plumlee'
 'Jakob Poeltl' 'Aleksej Pokusevski' 'Jordan Poole' 'Kevin Porter Jr.'
 'Michael Porter Jr.' 'Otto Porter Jr.' 'Bobby Portis'
 'Kristaps Porzi??is' 'Micah Potter' 'Dwight Powell' 'Norman Powell'
 'Joshua Primo' 'Taurean Prince' 'Payton Pritchard' 'Trevelin Queen'
 'Neemias Queta' 'Immanuel Quickley' 'Julius Randle' 'Austin Reaves'
 'Cam Reddish' 'Davon Reed' 'Paul Reed' 'Naz Reid' 'Nick Richards'
 'Josh Richardson' 'Austin Rivers' 'Duncan Robinson' 'Mitchell Robinson'
 'Jeremiah Robinson-Earl' 'Isaiah Roby' 'Derrick Rose' 'Terrence Ross'
 'Terry Rozier' 'Ricky Rubio' "D'Angelo Russell" 'Matt Ryan'
 'Domantas Sabonis' 'Olivier Sarr' 'Jordan Schakel' 'Admiral Schofield'
 'Jay Scrubb' 'Collin Sexton' 'Landry Shamet' "Day'Ron Sharpe"
 'Pascal Siakam' 'Chris Silva' 'Marko Simonovic' 'Anfernee Simons'
 'Jericho Sims' 'Marcus Smart' 'Dennis Smith Jr.' 'Ish Smith'
 'Jalen Smith' 'Xavier Sneed' 'Jaden Springer' 'Lamar Stevens'
 'Isaiah Stewart' 'Max Strus' 'Jalen Suggs' "Jae'Sean Tate" 'Jayson Tatum'
 'Terry Taylor' 'Garrett Temple' 'Daniel Theis' 'Cam Thomas'
 'Klay Thompson' 'JT Thor' 'Matisse Thybulle' 'Xavier Tillman Sr.'
 'Isaiah Todd' 'Obi Toppin' 'Juan Toscano-Anderson' 'Karl-Anthony Towns'
 'Gary Trent Jr.' 'P.J. Tucker' 'Myles Turner' 'Jonas Valan?i?nas'
 'Jarred Vanderbilt' 'Fred VanVleet' 'Devin Vassell' 'Gabe Vincent'
 'Nikola Vu?evi?' 'Dean Wade' 'Franz Wagner' 'Moritz Wagner'
 'Ish Wainright' 'Kemba Walker' 'Lonnie Walker IV' 'Duane Washington Jr.'
 'P.J. Washington' 'Yuta Watanabe' 'Lindy Waters III' 'Trendon Watford'
 'Russell Westbrook' 'Coby White' 'Derrick White' 'Joe Wieskamp'
 'Aaron Wiggins' 'Andrew Wiggins' 'Lindell Wigginton' 'Grant Williams'
 'Kenrich Williams' 'Patrick Williams' 'Robert Williams' 'Ziaire Williams'
 'Dylan Windler' 'Justise Winslow' 'Christian Wood' 'Delon Wright'
 'McKinley Wright IV' 'Gabe York' 'Thaddeus Young' 'Trae Young'
 'Omer Yurtseven' 'Cody Zeller' 'Ivica Zubac']

In [ ]:
# Print the actual and predicted points and assists for a sample player
player_name = input("Enter the player's name: ")
player_row = joined_data[joined_data['Player'] == player_name]
player_features = player_row[['Age_x', 'G_x', 'GS_x', 'MP_x', 'FG_x', 'FGA_x',
                       'Age_y', 'G_y', 'GS_y', 'MP_y', 'FG_y', 'FGA_y']]

Enter the player's name: Rodney McGruder

In [ ]:
# Get the actual points and assists for the player
pts_actual = player_row[['PTS_x']].values[0]
ast_actual = player_row[['AST_x']].values[0]

# Predict points and assists for the player
pts_predicted = model_pts.predict(player_features)[0]
ast_predicted = model_ast.predict(player_features)[0]

print("Player:", player_name)
print("2022-2023 Points:", pts_actual)
print("2023-2024 Predicted Points:", pts_predicted)
print("2022-2023 Assists:", ast_actual)
print("2023-2024 Predicted Assists:", ast_predicted)

Player: Cody Zeller
2022-2023 Points: [6.5]
2023-2024 Predicted Points: [6.35401103]
2022-2023 Assists: [0.7]
2023-2024 Predicted Assists: [1.51465809]

In [ ]:
joined_data = joined_data.rename(columns={
    'Age_x': 'Age_2022-2023',
    'G_x': 'G_2022-2023',
    'GS_x': 'GS_2022-2023',
    'MP_x': 'MP_2022-2023',
    'FG_x': 'FG_2022-2023',
    'FGA_x': 'FGA_2022-2023',
    'Age_y': 'Age_2021-2022',
    'G_y': 'G_2021-2022',
    'GS_y': 'GS_2021-2022',
    'MP_y': 'MP_2021-2022',
    'FG_y': 'FG_2021-2022',
    'FGA_y': 'FGA_2021-2022'
})

In [ ]:
# Create a copy of pandas_df
pandas_df_with_predictions = joined_data.copy()

# Add the predictions as new columns
pandas_df_with_predictions['2023-2024 Predicted Points'] = pts_predictions[:, 0]
pandas_df_with_predictions['2023-2024 Predicted Assists'] = ast_predictions[:, 0]

# Specify the path where you want to save the file
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Predicted_Data_Updated.csv'

# Save the DataFrame as a CSV file
pandas_df_with_predictions.to_csv(file_path, encoding='utf-8', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).